package com.juliuscanute.alfred.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAlfredAction = createDescriptorForAlfredAction();
  /*package*/ final ConceptDescriptor myConceptHostField = createDescriptorForHostField();
  /*package*/ final ConceptDescriptor myConceptKeyElement = createDescriptorForKeyElement();
  /*package*/ final ConceptDescriptor myConceptKeyField = createDescriptorForKeyField();
  /*package*/ final ConceptDescriptor myConceptKeyFieldReference = createDescriptorForKeyFieldReference();
  /*package*/ final ConceptDescriptor myConceptPathField = createDescriptorForPathField();
  /*package*/ final ConceptDescriptor myConceptSchemeField = createDescriptorForSchemeField();
  /*package*/ final ConceptDescriptor myConceptSinglePathField = createDescriptorForSinglePathField();
  /*package*/ final ConceptDescriptor myConceptSubtitleField = createDescriptorForSubtitleField();
  /*package*/ final ConceptDescriptor myConceptTitleField = createDescriptorForTitleField();
  /*package*/ final ConceptDescriptor myConceptUrlField = createDescriptorForUrlField();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    deps.aggregatedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAlfredAction, myConceptHostField, myConceptKeyElement, myConceptKeyField, myConceptKeyFieldReference, myConceptPathField, myConceptSchemeField, myConceptSinglePathField, myConceptSubtitleField, myConceptTitleField, myConceptUrlField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AlfredAction:
        return myConceptAlfredAction;
      case LanguageConceptSwitch.HostField:
        return myConceptHostField;
      case LanguageConceptSwitch.KeyElement:
        return myConceptKeyElement;
      case LanguageConceptSwitch.KeyField:
        return myConceptKeyField;
      case LanguageConceptSwitch.KeyFieldReference:
        return myConceptKeyFieldReference;
      case LanguageConceptSwitch.PathField:
        return myConceptPathField;
      case LanguageConceptSwitch.SchemeField:
        return myConceptSchemeField;
      case LanguageConceptSwitch.SinglePathField:
        return myConceptSinglePathField;
      case LanguageConceptSwitch.SubtitleField:
        return myConceptSubtitleField;
      case LanguageConceptSwitch.TitleField:
        return myConceptTitleField;
      case LanguageConceptSwitch.UrlField:
        return myConceptUrlField;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAlfredAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.juliuscanute.alfred", "AlfredAction", 0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x7ba9e6cfe6cfc808L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fd5d1e9a-b58d-43c7-9ef1-adfe2cf25cca(com.juliuscanute.alfred.structure)/8910907118334232584");
    b.version(2);
    b.aggregate("conceptField", 0x7ba9e6cfe6cfca91L).target(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x7ba9e6cfe6cfb739L).optional(false).ordered(true).multiple(false).origin("8910907118334233233").done();
    b.aggregate("keyField", 0x4c7ca092384ac145L).target(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x4c7ca09238492e49L).optional(false).ordered(true).multiple(true).origin("5511456593864737093").done();
    b.aggregate("titleField", 0x4c7ca09238492fa3L).target(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x4c7ca09238492e46L).optional(false).ordered(true).multiple(false).origin("5511456593864634275").done();
    b.aggregate("subtitleField", 0x4c7ca09238492fa6L).target(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x4c7ca09238492e8dL).optional(false).ordered(true).multiple(false).origin("5511456593864634278").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHostField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.juliuscanute.alfred", "HostField", 0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0xb85403e7a8790b6L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fd5d1e9a-b58d-43c7-9ef1-adfe2cf25cca(com.juliuscanute.alfred.structure)/830140343407579318");
    b.version(2);
    b.property("host", 0xb85403e7a8790bdL).type(PrimitiveTypeId.STRING).origin("830140343407579325").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKeyElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.juliuscanute.alfred", "KeyElement", 0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x2b916fb1028edb79L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fd5d1e9a-b58d-43c7-9ef1-adfe2cf25cca(com.juliuscanute.alfred.structure)/3139413221296757625");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKeyField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.juliuscanute.alfred", "KeyField", 0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x4c7ca09238492e49L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fd5d1e9a-b58d-43c7-9ef1-adfe2cf25cca(com.juliuscanute.alfred.structure)/5511456593864633929");
    b.version(2);
    b.aggregate("element", 0x2b916fb1028edba1L).target(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x2b916fb1028edb79L).optional(false).ordered(true).multiple(true).origin("3139413221296757665").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKeyFieldReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.juliuscanute.alfred", "KeyFieldReference", 0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x4c7ca092384db0dbL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.baseLanguage.structure.Expression", 0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fd5d1e9a-b58d-43c7-9ef1-adfe2cf25cca(com.juliuscanute.alfred.structure)/5511456593864929499");
    b.version(2);
    b.associate("keyField", 0x4c7ca092384db0dcL).target(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x4c7ca09238492e49L).optional(false).origin("5511456593864929500").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPathField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.juliuscanute.alfred", "PathField", 0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0xb85403e7a8790b7L);
    b.class_(false, false, false);
    b.origin("r:fd5d1e9a-b58d-43c7-9ef1-adfe2cf25cca(com.juliuscanute.alfred.structure)/830140343407579319");
    b.version(2);
    b.aggregate("paths", 0xb85403e7a879134L).target(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0xb85403e7a879112L).optional(true).ordered(true).multiple(true).origin("830140343407579444").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSchemeField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.juliuscanute.alfred", "SchemeField", 0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0xb85403e7a8790b8L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fd5d1e9a-b58d-43c7-9ef1-adfe2cf25cca(com.juliuscanute.alfred.structure)/830140343407579320");
    b.version(2);
    b.property("scheme", 0xb85403e7a8790b9L).type(PrimitiveTypeId.STRING).origin("830140343407579321").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSinglePathField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.juliuscanute.alfred", "SinglePathField", 0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0xb85403e7a879112L);
    b.class_(false, false, false);
    b.origin("r:fd5d1e9a-b58d-43c7-9ef1-adfe2cf25cca(com.juliuscanute.alfred.structure)/830140343407579410");
    b.version(2);
    b.property("path", 0xb85403e7a879113L).type(PrimitiveTypeId.STRING).origin("830140343407579411").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSubtitleField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.juliuscanute.alfred", "SubtitleField", 0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x4c7ca09238492e8dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fd5d1e9a-b58d-43c7-9ef1-adfe2cf25cca(com.juliuscanute.alfred.structure)/5511456593864633997");
    b.version(2);
    b.aggregate("expression", 0x4c7ca092384b746eL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("5511456593864782958").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTitleField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.juliuscanute.alfred", "TitleField", 0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x4c7ca09238492e46L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fd5d1e9a-b58d-43c7-9ef1-adfe2cf25cca(com.juliuscanute.alfred.structure)/5511456593864633926");
    b.version(2);
    b.aggregate("expression", 0x4c7ca092384b747aL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("5511456593864782970").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUrlField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.juliuscanute.alfred", "UrlField", 0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x7ba9e6cfe6cfb739L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fd5d1e9a-b58d-43c7-9ef1-adfe2cf25cca(com.juliuscanute.alfred.structure)/8910907118334228281");
    b.version(2);
    b.property("url", 0x7ba9e6cfe6cfb73aL).type(PrimitiveTypeId.STRING).origin("8910907118334228282").done();
    b.aggregate("scheme", 0xb85403e7a8790bfL).target(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0xb85403e7a8790b8L).optional(false).ordered(true).multiple(false).origin("830140343407579327").done();
    b.aggregate("host", 0xb85403e7a8790c1L).target(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0xb85403e7a8790b6L).optional(false).ordered(true).multiple(false).origin("830140343407579329").done();
    b.aggregate("path", 0xb85403e7a8790c4L).target(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0xb85403e7a8790b7L).optional(false).ordered(true).multiple(false).origin("830140343407579332").done();
    return b.create();
  }
}
