package com.juliuscanute.alfred.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class AlfredAction_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("import urllib3");
    tgs.newLine();
    tgs.append("import json");
    tgs.newLine();
    tgs.newLine();
    tgs.append("def request(method, url):");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("http = urllib3.PoolManager()");
    tgs.newLine();
    tgs.indent();
    tgs.append("request = http.request(method, url)");
    tgs.newLine();
    tgs.indent();
    tgs.append("return json.loads(request.data.decode('utf-8'))");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.newLine();
    tgs.append("def key(response):");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("value = response['resuls']['name']");
    tgs.newLine();
    tgs.indent();
    tgs.append("return value");
    ctx.getBuffer().area().decreaseIndent();
    tgs.newLine();
    tgs.newLine();
    tgs.append("def get_title():");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("return \"title\"");
    ctx.getBuffer().area().decreaseIndent();
    tgs.newLine();
    tgs.newLine();
    tgs.append("if __name__ == u\"__main__\":");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("print('");
    UrlField_TextGen.urlfield(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.conceptField$s4gN), ctx);
    tgs.append("')");
    ctx.getBuffer().area().decreaseIndent();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink conceptField$s4gN = MetaAdapterFactory.getContainmentLink(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x7ba9e6cfe6cfc808L, 0x7ba9e6cfe6cfca91L, "conceptField");
  }
}
