package com.juliuscanute.alfred.textGen;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public abstract class PathField_TextGen {
  public static void pathField(SNode pathField, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    List<SNode> paths;
    paths = SLinkOperations.getChildren(pathField, LINKS.paths$qvxG);
    String finalPath = "/";
    for (int count = 0; count < paths.size(); count++) {
      SNode singlePathField;
      singlePathField = ListSequence.fromList(paths).getElement(count);
      finalPath += SPropertyOperations.getString(singlePathField, PROPS.path$qgdk);
      if (count != paths.size() - 1) {
        finalPath += "/";
      }
    }
    tgs.append(finalPath);
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink paths$qvxG = MetaAdapterFactory.getContainmentLink(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0xb85403e7a8790b7L, 0xb85403e7a879134L, "paths");
  }

  private static final class PROPS {
    /*package*/ static final SProperty path$qgdk = MetaAdapterFactory.getProperty(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0xb85403e7a879112L, 0xb85403e7a879113L, "path");
  }
}
