package com.juliuscanute.alfred.textGen;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public abstract class SchemeField_TextGen {
  public static void schemeField(SNode schemeField, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getString(schemeField, PROPS.scheme$mIYk));
  }

  private static final class PROPS {
    /*package*/ static final SProperty scheme$mIYk = MetaAdapterFactory.getProperty(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0xb85403e7a8790b8L, 0xb85403e7a8790b9L, "scheme");
  }
}
