package com.juliuscanute.alfred.textGen;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public abstract class UrlField_TextGen {
  public static void urlfield(SNode urlField, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    SchemeField_TextGen.schemeField(SLinkOperations.getTarget(urlField, LINKS.scheme$rsm6), ctx);
    tgs.append("://");
    HostField_TextGen.hostField(SLinkOperations.getTarget(urlField, LINKS.host$rsO8), ctx);
    PathField_TextGen.pathField(SLinkOperations.getTarget(urlField, LINKS.path$rysw), ctx);
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink scheme$rsm6 = MetaAdapterFactory.getContainmentLink(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x7ba9e6cfe6cfb739L, 0xb85403e7a8790bfL, "scheme");
    /*package*/ static final SContainmentLink host$rsO8 = MetaAdapterFactory.getContainmentLink(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x7ba9e6cfe6cfb739L, 0xb85403e7a8790c1L, "host");
    /*package*/ static final SContainmentLink path$rysw = MetaAdapterFactory.getContainmentLink(0xd6f1829c44d840a5L, 0xb1c7596bc2927669L, 0x7ba9e6cfe6cfb739L, 0xb85403e7a8790c4L, "path");
  }
}
